//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SesanPLCMonitoring
    {
        public int ID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> RemoteBit { get; set; }
        public Nullable<bool> SimulationBit { get; set; }
        public Nullable<bool> CV1Bottom { get; set; }
        public Nullable<bool> CV1Overload { get; set; }
        public Nullable<bool> CV1Running { get; set; }
        public Nullable<bool> CV2Bottom { get; set; }
        public Nullable<bool> CV2Overload { get; set; }
        public Nullable<bool> CV2Running { get; set; }
        public Nullable<double> DrainLevel1 { get; set; }
        public Nullable<double> DrainLevel2 { get; set; }
    }
}
