//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Id { get; set; }
        public Nullable<double> MucNuoc { get; set; }
        public Nullable<double> LuuLuong { get; set; }
        public Nullable<bool> IsPushedToTNMT { get; set; }
        public System.DateTime Date { get; set; }
    }
}
