//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Parameter
    {
        public int ID { get; set; }
        public Nullable<double> K_ChuaCoHep { get; set; }
        public Nullable<double> K_CoHepNgang { get; set; }
        public Nullable<double> K_CoHepDung { get; set; }
        public Nullable<double> K_LuuLuong { get; set; }
        public Nullable<double> H_MayPhat { get; set; }
        public Nullable<double> H_CoKhi { get; set; }
        public Nullable<double> H_Turbine { get; set; }
        public Nullable<double> CaoTrinhNguongTran { get; set; }
        public Nullable<double> ChieuDaiDapTran { get; set; }
        public Nullable<double> CaoTrinhNguongKenhXa { get; set; }
        public Nullable<double> ChieuRongKenhXa { get; set; }
        public Nullable<double> DungTichHuuIch1 { get; set; }
        public Nullable<double> DungTichHuuIch2 { get; set; }
        public Nullable<double> DungTichHuuIch3 { get; set; }
        public Nullable<double> DungTichHuuIch4 { get; set; }
        public Nullable<double> MucNuocChet { get; set; }
        public Nullable<double> DungTichHoMNC { get; set; }
        public Nullable<double> K_DCTT { get; set; }
        public Nullable<double> DCTT_QuyDinh { get; set; }
        public string Nhamay { get; set; }
        public Nullable<bool> DCTT_Toggle { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> SampleSize { get; set; }
        public Nullable<bool> Upstream_Cal_Toggle { get; set; }
    }
}
