//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuantracEntities : DbContext
    {
        public QuantracEntities()
            : base("name=QuantracEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Data> DB_Data { get; set; }
        public virtual DbSet<DB_Measurement> DB_Measurement { get; set; }
        public virtual DbSet<DB_Parameter> DB_Parameter { get; set; }
        public virtual DbSet<DB_PLCConfiguration> DB_PLCConfiguration { get; set; }
        public virtual DbSet<DB_Service> DB_Service { get; set; }
        public virtual DbSet<DB_User> DB_User { get; set; }
    }
}
