//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Measurement
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> UpstreamWaterLevel_m { get; set; }
        public Nullable<double> DownstreamWaterLevel_m { get; set; }
        public Nullable<double> Qve_Ho { get; set; }
        public Nullable<double> Qoverflow { get; set; }
        public Nullable<double> QcmH1H2H3 { get; set; }
        public Nullable<double> Qminflow { get; set; }
        public Nullable<double> Qve_Hadu { get; set; }
        public Nullable<double> Drain_Level1 { get; set; }
        public Nullable<double> Qve_HoDB { get; set; }
        public Nullable<double> Reserve_Water { get; set; }
        public Nullable<double> Qminflow_TT { get; set; }
        public Nullable<double> H1_MW { get; set; }
        public Nullable<double> H2_MW { get; set; }
        public Nullable<double> H3_MW { get; set; }
        public Nullable<double> QcmH1 { get; set; }
        public Nullable<double> QcmH2 { get; set; }
        public Nullable<double> QcmH3 { get; set; }
        public Nullable<double> DeltaQsb { get; set; }
        public Nullable<double> Qve_TT { get; set; }
        public Nullable<double> Qve_TB { get; set; }
    }
}
