//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaksrongDBEntities : DbContext
    {
        public DaksrongDBEntities()
            : base("name=DaksrongDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Sesan_2PLC> DB_Sesan_2PLC { get; set; }
        public virtual DbSet<DB_SesanMeasurement> DB_SesanMeasurement { get; set; }
        public virtual DbSet<DB_SesanParameter> DB_SesanParameter { get; set; }
        public virtual DbSet<DB_SesanPLCConfiguration> DB_SesanPLCConfiguration { get; set; }
        public virtual DbSet<DB_SesanService> DB_SesanService { get; set; }
    }
}
