//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_IAMO_Measurement
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> H1_ActivePower { get; set; }
        public Nullable<decimal> H2_ActivePower { get; set; }
        public Nullable<decimal> H1_ReactivePower { get; set; }
        public Nullable<decimal> H2_ReactivePower { get; set; }
        public Nullable<decimal> QcmH1 { get; set; }
        public Nullable<decimal> QcmH2 { get; set; }
        public Nullable<bool> IsPushedToThuyLoi { get; set; }
    }
}
