//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_IAMO_Configuration
    {
        public int Id { get; set; }
        public short SlaveID1 { get; set; }
        public int AddressP1 { get; set; }
        public int AddressQ1 { get; set; }
        public Nullable<decimal> TiSoP1 { get; set; }
        public Nullable<decimal> TiSoQ1 { get; set; }
        public decimal HieuSuatMayPhat { get; set; }
        public decimal HieuSuatCoKhi { get; set; }
        public decimal HieuSuatTurbine { get; set; }
        public decimal CotAp { get; set; }
        public bool BasedOnTiSo { get; set; }
        public string Portname { get; set; }
        public int Baudrate { get; set; }
        public short SlaveID2 { get; set; }
        public int AddressP2 { get; set; }
        public int AddressQ2 { get; set; }
        public Nullable<decimal> TiSoP2 { get; set; }
        public Nullable<decimal> TiSoQ2 { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
