//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SesanPLCConfiguration
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> CPUType { get; set; }
        public Nullable<int> Rack { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> RemoteBit { get; set; }
        public Nullable<bool> SimulationBit { get; set; }
        public Nullable<bool> CV1Bottom { get; set; }
        public Nullable<bool> CV1Overload { get; set; }
        public Nullable<bool> CV1Running { get; set; }
        public Nullable<bool> CV2Bottom { get; set; }
        public Nullable<bool> CV2Overload { get; set; }
        public Nullable<bool> CV2Running { get; set; }
        public Nullable<double> DrainLevel1 { get; set; }
        public Nullable<double> DrainLevel2 { get; set; }
        public Nullable<bool> KU1 { get; set; }
        public Nullable<bool> KD1 { get; set; }
        public Nullable<bool> KU2 { get; set; }
        public Nullable<bool> KD2 { get; set; }
        public Nullable<int> ScheduleDayOn { get; set; }
        public Nullable<System.TimeSpan> ScheduleTimeOn { get; set; }
        public Nullable<int> ScheduleDayOff { get; set; }
        public Nullable<System.TimeSpan> ScheduleTimeOff { get; set; }
        public Nullable<bool> KU1_SIM { get; set; }
        public Nullable<bool> KD1_SIM { get; set; }
        public Nullable<bool> KU2_SIM { get; set; }
        public Nullable<bool> KD2_SIM { get; set; }
        public Nullable<bool> ManBit { get; set; }
        public Nullable<bool> ScheduleBit { get; set; }
    }
}
