//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusG.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuantracEntities : DbContext
    {
        public QuantracEntities()
            : base("name=QuantracEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_DakHnol> DB_DakHnol { get; set; }
        public virtual DbSet<DB_DakHnolMeasurement> DB_DakHnolMeasurement { get; set; }
        public virtual DbSet<DB_DakHnolParameter> DB_DakHnolParameter { get; set; }
        public virtual DbSet<DB_DakHnolPLCConfiguration> DB_DakHnolPLCConfiguration { get; set; }
        public virtual DbSet<DB_DakHnolService> DB_DakHnolService { get; set; }
        public virtual DbSet<DB_IAMO_Measurement> DB_IAMO_Measurement { get; set; }
        public virtual DbSet<DB_IAMO_Configuration> DB_IAMO_Configuration { get; set; }
    }
}
